### ISSUE TITLE
Impostare la data di partenza ad oggi

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/timemapsicilia#1]
Ciao @cirospat ,
quando si apre la pagina, si parte da una data "vecchia". 

Io imposterei la data di "start" a "today".

![image](https://cloud.githubusercontent.com/assets/30607/8980769/6f8c6514-36b3-11e5-8b8f-cf5a43eb07ce.png)

**Comment by cirospat** [comment]
d'accordo

2015-07-30 12:07 GMT+02:00 Andrea Borruso notifications@github.com:

**Comment by cirospat** [comment]
fatto

2015-07-30 12:09 GMT+02:00 ciro spataro cirospat@gmail.com:

**Comment by aborruso** [comment]
@cirospat visto che la cosa l'hai risolta, puoi chiudere la issue (sono soddisfazioni).

Nella pagina su github, trovi il tasto "Close issue". E puoi pure commentare e chiudere.
